extends:
  - "@commitlint/config-conventional"
rules:
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - release
      - revert
      - test
help: |
  **Possible types**:
  `build`:    Changes that affect the build system or external dependencies (example scopes: yarn, npm)
  `chore`:    No production code change. Updating grunt tasks etc;
  `ci`:       Changes to our CI configuration files and scripts (example scopes: Github Actions, Travis, Circle CI, BrowserStack, SauceLabs)
  `docs`:     Adds or alters documentation. (example scopes: readme, worker, code_of_conduct, contributors)
  `feat`:     Adds a new feature.
  `fix`:      Solves a bug.
  `perf`:     Improves performance.
  `refactor`: Rewrites code without feature, performance or bug changes.
  `release`:  
  `revert`:   Changes that reverting other changes
  `test`:     Adds or modifies tests. (example scopes: functionals, unit-tests)
