env:
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
ignorePatterns:
  - "src/types/**/*"
  - "dist"
  - "node_modules"
  - "yarn.lock"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint"
root: true
rules:
  no-undef: "warn"
  no-unused-vars: "warn"
  no-extra-boolean-cast: "off"
  no-constant-condition: "off"
  no-async-promise-executor: "off"
