env:
  es2020: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
ignorePatterns:
  - "src/types/**/*"
  - "dist"
  - "node_modules"
  - "yarn.lock"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
root: true
rules:
  no-undef: "warn"
  simple-import-sort/imports: "warn"
  simple-import-sort/exports: "warn"
