specVersion: 0.2.0
name: metadot-subql
version: 0.0.4
description: subquery indexer for metadot
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c"
  endpoint: wss://acala-polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  chaintypes:
    file: ./chaintypes.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 763551
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: NewMultisig
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigApproval
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigExecuted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigCancelled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchCompleted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchInterrupted
        - handler: handleCall
          kind: substrate/CallHandler
