specVersion: 0.2.0
name: metadot-multisig
version: 0.0.4
description: multisig subquery for metadot
schema:
  file: ./schema.graphql
network:
  # Polkadot
  # genesisHash: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
  # endpoint: wss://rpc.polkadot.io
  # endpoint: wss://polkadot.api.onfinality.io/public-ws
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  # KSM
  # genesisHash: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
  # endpoint: "wss://kusama.api.onfinality.io/public-ws"
  # dictionary: "https://api.subquery.network/sq/subquery/dictionary-kusama"
  # WESTEND
  genesisHash: "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"
  endpoint: wss://westend.api.onfinality.io/public-ws
  # ASTAR
  # genesisHash: "0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6"
  # endpoint: wss://astar.api.onfinality.io/public-ws
  # dictionary:
  # ACALA
  # genesisHash: "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c"
  # endpoint: wss://acala-polkadot.api.onfinality.io/public-ws
  # dictionary:
  # KARURA
  # genesisHash: "0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b"
  # endpoint: wss://karura.api.onfinality.io/public-ws
  # dictionary:
  # SHIDEN
  # genesisHash: "0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108"
  # endpoint: wss://shiden.api.onfinality.io/public-ws
  # dictionary:
  # WESTEND
  # genesisHash: "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"
  # endpoint: wss://westend.api.onfinality.io/public-ws
  # dictionary:
  # CONTEXTFREE
  # genesisHash: "0x6254c948b5eb7199a112cb308be3385c39c8c942625540ac749c77fe2aebc299"
  # endpoint: wss://contextfree.api.onfinality.io/public-ws
  # dictionary: https://api.subquery.network/sq/subquery/contextfree-dictionary
  # chaintypes:
  #   file: ./chaintypes/contextfree.yaml
dataSources:
  - kind: substrate/Runtime
    # startBlock: 1
    # startBlock: 2629236 # context free
    # startBlock: 1738638 # Karura
    # startBlock: 763551 # Acala
    # startBlock: 780104 # Astar
    # startBlock: 780,104 # Polkadot
    # startBlock: 10340000 # Kusama
    startBlock: 10478363 # Westend
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            # A new multisig operation has begun. [approving, multisig, call_hash]
            method: NewMultisig
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            # A multisig operation has been approved by someone. [approving, timepoint, multisig, call_hash]
            method: MultisigApproval
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            # A multisig operation has been executed. [approving, timepoint, multisig, call_hash]
            method: MultisigExecuted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            # A multisig operation has been cancelled. [cancelling, timepoint, multisig, call_hash]
            method: MultisigCancelled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchCompleted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchInterrupted
        # saves every extrinsic call on the chain
        - handler: handleCall
          kind: substrate/CallHandler
