specVersion: 1.0.0
name: metadot-subql
version: 0.0.4
runner:
  node:
    name: "@subql/node"
    version: 1.0.0
  query:
    name: "@subql/query"
    version: 1.0.0
description: subquery indexer for metadot
repository: https://github.com/ahmedali8/metadot-subql
schema:
  file: ./schema.graphql
network:
  chainId: "0x8b290fa39a8808f29d7309ea99442c95bf964838aef14be5a6449ae48f8a5f1f"
  endpoint: wss://bifrost-rpc.testnet.liebi.com/ws
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./chaintypes.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 180859
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: NewMultisig
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigApproval
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigExecuted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigCancelled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchCompleted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchInterrupted
