specVersion: 0.2.0
name: metadot-subql
version: 0.0.4
description: subquery indexer for metadot
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed"
  endpoint: wss://bifrost-rpc.liebi.com/ws
  chaintypes:
    file: ./chaintypes.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1638328
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: NewMultisig
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigApproval
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigExecuted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: multisig
            method: MultisigCancelled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchCompleted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchInterrupted
        - handler: handleCall
          kind: substrate/CallHandler
