name: Create release

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  create-all-network-branches:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get package.json version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Print package version
        run: echo ${{ steps.package-version.outputs.current-version }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.package-version.outputs.current-version }}
          prerelease: true
          title: "Deployed Build v${{ steps.package-version.outputs.current-version }}"
